server:
    port: 9080
    context-path:

logging:
    path: target
    file: scheduler.log
    level:
        tk.mybatis: INFO

spring:
    datasource:
        url: jdbc:mysql://192.168.5.10:3306/dnkx_manage
        username: root
        password: root